[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
showErrorDetails = true
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[runner]
fastReruns = true
magicEnabled = false
